# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      serviceAccountName: {{.ServiceAccountName}}
      hostPID: {{.HostPID}}
      restartPolicy: Never
      nodeName: {{.NodeName}}
      hostNetwork: {{.HostNetwork}}
      containers:
        - name: job
          image: {{.Image}}
          command: {{.CommandJson}}
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run-kubesan-nbd
              mountPath: /run/kubesan/nbd
          securityContext:
            privileged: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: run-kubesan-nbd
          hostPath:
            path: /run/kubesan/nbd
            type: DirectoryOrCreate
