# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvmlockd
  namespace: subprovisioner
spec:
  selector:
    matchLabels: &labels
      subprovisioner.gitlab.io/component: lvmlockd
  template:
    metadata:
      labels: *labels
    spec:
      shareProcessNamespace: true
      containers:
        - name: lvmlockd
          image: quay.io/subprovisioner/subprovisioner:v0.0.2
          command:
            - scripts/lvmlockd.sh
            - $(HOST_IP)
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run-lvm
              mountPath: /run/lvm
            - name: run-sanlock
              mountPath: /run/sanlock
          securityContext:
            privileged: true
        - name: sanlock
          image: quay.io/subprovisioner/subprovisioner:v0.0.2
          command:
            - scripts/sanlock.sh
            - $(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run-sanlock
              mountPath: /run/sanlock
          securityContext:
            privileged: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: run-lvm
          hostPath:
            path: /run/subprovisioner/lvm
            type: DirectoryOrCreate
        - name: run-sanlock
          emptyDir:
