# SPDX-License-Identifier: Apache-2.0

# used by package pkg/subprovisioner/volumemanager
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-volumemanager
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, update]
  - apiGroups: [""]
    resources: [services]
    verbs: [create, delete]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [create, delete, get]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, delete, get]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, update]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-volumemanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subprovisioner-volumemanager
subjects:
  - kind: ServiceAccount
    name: csi-controller-plugin
    namespace: subprovisioner
  - kind: ServiceAccount
    name: csi-node-plugin
    namespace: subprovisioner

---

# used by package pkg/subprovisioner/csi/controller
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-csi-controller
rules:
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, delete, get]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-csi-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subprovisioner-csi-controller
subjects:
  - kind: ServiceAccount
    name: csi-controller-plugin
    namespace: subprovisioner

---

# used by image registry.k8s.io/sig-storage/csi-provisioner
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-csi-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: subprovisioner-csi-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subprovisioner-csi-provisioner
subjects:
  - kind: ServiceAccount
    name: csi-controller-plugin
    namespace: subprovisioner
