# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-controller-manager
  namespace: kubesan-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-controller-manager
  namespace: kubesan-system
