# SPDX-License-Identifier: Apache-2.0

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubesan
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
priority:
allowHostNetwork: false
allowHostPorts: false
allowedCapabilities: []
allowHostPID: true
allowHostIPC: false
readOnlyRootFilesystem: false
requiredDropCapabilities: []
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:openshift-storage:csi-controller-plugin
  - system:serviceaccount:openshift-storage:csi-node-plugin
  - system:serviceaccount:openshift-storage:cluster-controller-manager
  - system:serviceaccount:openshift-storage:node-controller-manager
volumes:
  - configMap
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - secret
