# SPDX-License-Identifier: Apache-2.0

apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: subprovisioner.gitlab.io
spec:
  attachRequired: false  # skip Controller{Publish,Unpublish}Volume()

---

apiVersion: v1
kind: Namespace
metadata:
  name: subprovisioner
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blobpools.subprovisioner.gitlab.io
spec:
  group: subprovisioner.gitlab.io
  names:
    kind: BlobPool
    plural: blobpools
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.activeOnNode
          name: Active On
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [blobs, activeOnNode, holders]
              properties:
                blobs:
                  type: array
                  items:
                    type: string
                activeOnNode:
                  type: string
                  nullable: true
                holders:
                  type: array
                  items:
                    type: object
                    required: [blob, node, cookie]
                    properties:
                      blob:
                        type: string
                      node:
                        type: string
                      cookie:
                        type: string
